### ISSUE TITLE
create page footer

### ISSUE THREAD

**Issue by mcwiekala** [mcwiekala/CodersCamp2021.Project.Web-Development-Basics#26]
![Screenshot from 2021-12-02 20-31-12](https://user-images.githubusercontent.com/80964094/144490224-8ba4b475-e7e1-4709-af07-0d25e7d91813.png)

**Comment by Dawid-Dwk** [comment]
https://github.com/mcwiekala/CodersCamp2021.Project.Web-Development-Basics/pull/33
