### ISSUE TITLE
create DIV as a background for text

### ISSUE THREAD

**Issue by mcwiekala** [mcwiekala/CodersCamp2021.Project.Web-Development-Basics#29]
![Screenshot from 2021-12-02 20-26-55](https://user-images.githubusercontent.com/80964094/144489899-f8110f99-fe69-45a5-903f-bf0de4feb787.png)

**Comment by sylwiagie** [comment]
https://github.com/mcwiekala/CodersCamp2021.Project.Web-Development-Basics/pull/30

**Comment by mcwiekala** [comment]
please create this section on main page:

![image](https://user-images.githubusercontent.com/80964094/144758210-7947aad8-e4b1-44ec-b6e6-f16b842f489f.png)

**Comment by sylwiagie** [comment]
@mcwiekala  https://github.com/mcwiekala/CodersCamp2021.Project.Web-Development-Basics/pull/41

**Comment by sylwiagie** [comment]
@mcwiekala przesyłam nowy branch ze zmianami https://github.com/mcwiekala/CodersCamp2021.Project.Web-Development-Basics/pull/47
